ext/libv8/location.rb
ext/libv8/paths.rb

The new V8 has split some of its functionality to other objects. These are `libplatform` and `libbase` and are required for something to use the V8 API.
Also, they now assume the V8 headers can be accessed with the path of `include/<name>.h`. For example, you cannot include `v8.h` if you point directly to the `include` directory inside V8. You must point to the V8 directory itself and then include from `include/*`.
Without these changes V8 cannot be used by The ruby racer.
I'm not sure wether the change in `ext/libv8/location.rb` is correct. Should the argument to `find_header` include `include/` or `libplatform/` or neither?
I want to merge this so that the TRR PR ( https://github.com/cowboyd/therubyracer/pull/334 ) starts working without my libv8 fork.

Change includes and object paths for V8 3.31 compatibility (trunk)

---

ext/libv8/location.rb
spec/location_spec.rb

Before this change, the Makefile didn't tell the linker to link libv8:
LIBS = $(LIBRUBYARG_SHARED) -lpthread  -lpthread -lrt -ldl -lcrypt -lm   -lc
Now it does:
LIBS = $(LIBRUBYARG_SHARED) -lv8 -lpthread  -lpthread -lrt -ldl -lcrypt -lm   -lc

Properly link to the system's libv8

---

Rakefile
appveyor.yml
ext/libv8/builder.rb
ext/libv8/checkout.rb
ext/libv8/patcher.rb
patches/mingw-generate-makefiles.sh

Adds windows support using mingw compiler that comes with rubyinstaller's devkit.
Also requires Python27 (official windows build) and msysgit.
To build, open cmd.exe shell
> set PATH=%PATH%;C:\Python27;C:\Program Files (x86)\Git\bin
> c:\ruby-devkit-mingw64\devkitvars.bat
> bundle install
> bundle exec rake compile
mingw-generate-makefiles.sh script is a modified version from v8 source (modification just adds x64 target).

Added support for windows platforms using mingw.

---

ext/libv8/paths.rb
spec/location_spec.rb

The library and include flags were not escaped until now and this caused
issues when there were spaces in them. This fixes #164.

Escape the library and include paths

---

ext/libv8/patcher.rb
patches/clang51/no-unused-variable.patch

I had some [issues](https://github.com/cowboyd/therubyracer/issues/301#issuecomment-60460635) with libv8 3.11 after upgrade to OS X 10.10, and after some investigation I have fixed it by applying [this](https://github.com/cowboyd/libv8/pull/124) patch and installing libv8 manually.
Here is same patch but for 3.11 branch, hope this will help someone!

Add missing flag to OS X clang flag (for 3.11 libv8)

---

Rakefile
ext/libv8/checkout.rb

* for some reason, the git clean task inside the gyp directory was
returning an exit status of `1` even though it was cleaning out
files. Just ignore the exit status
* chomp the output of the `git-svn` invocation. At least on OSX, it was
throwing a specious warning about "-f" not being a valid command, and
if the force checkout was actually necessary, it was failing

fix checkout and clean tasks

---

.gitignore
Rakefile
release/x86-linux/Vagrantfile
release/x86_64-linux/Vagrantfile

I'm tired of our releases getting held up because building the binaries
is such a yak shave. We're in dire need of some automation. I tried
spiking some things out with Docker, but for the time being, it was
easier to just go with Vagrant.
Currently, our release process for binary gems involves
1. a source release at an even point (e.g. 3.16.14.8)
2. a version bump to serve as the basis for binary releases
3. a mish-mash of gem builds and pushes for osx, linux, freebsd, etc...
In order to make things eaiser for us to manage these binary builds, I'm
proposing a standardized build using Vagrant. For each supported
release, a Vagrant file goes into /release/<arch>/Vagrantfile
The vagrantfile is responsible for provisioning a modern
ruby toolchain including bundler, git, git-svn, ruby and …

framework for building binary gems

---

ext/libv8/patcher.rb
patches/clang70/no-unused-local-typedefs.patch

I can build for the time being with The Xcode 7.0 and the OS X El Capitan 10.11.

add a patch for clang 7.0

---

ext/libv8/location.rb
ext/libv8/paths.rb
spec/location_spec.rb

in 4.5.x, v8 starts expecting the include paths to contain the root of
the v8 source directory, and everywhere it had previously referenced
`v8.h`, it now references `include/v8.h`. insted of 'v8-profiler.h', it
refererces 'include/v8-profiler.h', etc...
This adds a test to make sure it can find 'include/v8.h' in the include
path as part of the installation verification.

update location of v8 include path

---

Rakefile

The chromium depot tools have problems with the /vagrant project
directory causing the new build process to fail.
https://github.com/pristineio/webrtc-build-scripts/issues/50
Moving the build into the home directory and not the shared project
directory fixed things right up. The binary gem is copied into the
shared folder at the end.

build libv8 in vagrant home directory

---

Rakefile

Was not including include/libplatform/libplatform.h in the binary gem because it was not a recursive dir glob.

Include all header files

---

.travis.yml

http://docs.travis-ci.com/user/migrating-from-legacy

use container based builds on travis

---

Rakefile
release/x86-linux/Vagrantfile
release/x86_64-linux/Vagrantfile

* doing a full clone of the depot tools. I thought that I could save
some time, but it means that building the binaries is not idempotent
* using rvm instead of system ruby

enhance the binary builders

---

Rakefile
ext/libv8/arch.rb
ext/libv8/builder.rb
release/x86_64-freebsd10/Vagrantfile

Things to keep in mind:
1. FreeBSD [does not support VirtualBox shared folders][vboxsf]. This means that one has to resort to using [alternative means][shared folders] of synchronisation of folders. I managed to test this with [rsync] but it only syncs one way -- host -> guest. There's also [NFS], however I did not manage to make it work on my Linux system. It should, in theory, work out of the box on mac, as stated in the 'Prerequisites' section of its documentation.
2. For some reason on FreeBSD gclient replaces the v8 Makefile with [this one][Makefile]. I have absolutely no idea why.
[nfs]: https://docs.vagrantup.com/v2/synced-folders/nfs.html
[rsync]: https://docs.vagrantup.com/v2/synced-folders/rsync.html
[shared folders]: https://docs.vagrantup.com/v2/synced-folders/index.html …

FreeBSD Vagrant box

---

.travis.yml

I like how using GCC adds an hour to overall build time...

Install and use g++ 4.8 in Travis

---

.travis.yml
ext/libv8/patcher.rb
patches/clang73/no-shift-negative-value.patch

This adds the -Wno-shift-negative-value flag to Clang. Clang 7.3 was introduced
in OSX with XCode 7.3.
Without this flag, compiling with Clang 7.3 fails with errors such as:
In file included from ../src/elements.h:32:
../src/objects.h:5252:44: error: shifting a negative signed value is undefined
[-Werror,-Wshift-negative-value]
static const int kElementsKindMask = (-1 << kElementsKindShift) &
~~ ^
../src/objects.h:7386:36: error: shifting a negative signed value is undefined
[-Werror,-Wshift-negative-value]
(~kMaxCachedArrayIndexLength << kArrayIndexHashLengthShift) |
~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
2 errors generated.

Add patch to allow build with clang 7.3

---

.travis.yml

Some Ruby versions where using a very old Bundler version.

Fix travis Linux tests

---

ext/libv8/checkout.rb

This seemed to cause an issue whenever there are no man pages installed
for git-svn.

Fix the check for git-svn

---

ext/libv8/location.rb

Every time I run into this message I struggle to understand what it's telling me to do.
This new error message clearly state the option that caused it (`--with-system-v8`) 
and it clearly focuses on the problem at hand: the system v8 wasn't found.
This commit also fixes the typos and removes the unnecessary signature.

Improve --with-system-v8 error message

---

patches/disable-xcode-debugging.patch

This lower the macOS Gem size from 147MB to 2.4MB.

Do not embed debug symbols in macOS libraries

---

.travis.yml
CHANGELOG.md
README.md
lib/libv8/version.rb
libv8.gemspec

* I have requested TravisCI to extend timeout from 50m to 120m
* Bump to 7.3.495.0
* Drop testing against Ruby 2.4 (EOL) and rbx (precompiled version is old)
* Test against Ruby 2.6 and 2.7
* Drop testing with XCode 9.2 (the upstream tooling yield dylib error) - the objective now is to get a green build to unblock development - we could revisit this in a separate PR

Bump to 7.3.495.0

---

.gitignore
.travis.yml
CHANGELOG.md
README.md
Rakefile
ext/libv8/builder.rb
lib/libv8/version.rb

i.e. Use last good version before build error
Using bisect, I was able to find that the build error we saw in #300 and #299 was introduced in https://github.com/v8/v8/commit/5bbca548e9841d25645e0ed077638b1d96bd1f07, so let's use the version before that one while we wait for upstream to merge the fix I submitted (https://bugs.chromium.org/p/v8/issues/detail?id=10708)
closes #298, #299 and #281

Update to 8.4.255

---

.travis.yml
Rakefile

Although any v8 OSX compile will run on any Mac OS version down to 10.10, RubyGems requires us to submit all of the different platforms seperately. This means that instead of running CI platforms for every OSX version we support, we can instead just create the gem on 1 platform, and then repackage it for all of the other platforms.﻿This avoids having to do dirty magic like convincing v8 to build with an older macos API version, which we would need to do to get v8 to compile on a 10.13 buildbot

Update mac OS build configuration
